# Generated by Django 3.2.9 on 2022-01-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20220105_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vehicle_no',
            field=models.CharField(max_length=200),
        ),
    ]
